package com.abctreinamentos;
// Generated 02/01/2019 15:52:06 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "CURSO")
public class Curso implements Serializable {

	private static final long serialVersionUID = -2018377179712009938L;
	private int cdcurso;
	private String nome;
	private double valor;
	private String url;
	private Set<Pagamento> pagamentos = new HashSet<Pagamento>(0);

	public Curso() {
	}

	public Curso(int cdcurso, String nome, double valor, String url) {
		this.cdcurso = cdcurso;
		this.nome = nome;
		this.valor = valor;
		this.url = url;
	}

	public Curso(int cdcurso, String nome, double valor, String url, Set<Pagamento> pagamentos) {
		this.cdcurso = cdcurso;
		this.nome = nome;
		this.valor = valor;
		this.url = url;
		this.pagamentos = pagamentos;
	}

	@Id

	@Column(name = "CDCURSO", unique = true, nullable = false, precision = 22, scale = 0)
	public int getCdcurso() {
		return this.cdcurso;
	}

	public void setCdcurso(int cdcurso) {
		this.cdcurso = cdcurso;
	}

	@Column(name = "NOME", nullable = false, length = 80)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "VALOR", nullable = false, precision = 22, scale = 0)
	public double getValor() {
		return this.valor;
	}

	public void setValor(double valor) {
		this.valor = valor;
	}

	@Column(name = "URL", nullable = false, length = 80)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "curso")
	public Set<Pagamento> getPagamentos() {
		return this.pagamentos;
	}

	public void setPagamentos(Set<Pagamento> pagamentos) {
		this.pagamentos = pagamentos;
	}

	@Override
	public String toString() {
		return "Curso - código: " + cdcurso + ", nome: " + nome + ", valor: " + String.format("%.2f", valor) + ", url: " + url;
	}
}
