package com.abctreinamentos;
// Generated 02/01/2019 15:52:06 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pagamento generated by hbm2java
 */
@Entity
@Table(name = "PAGAMENTO")
public class Pagamento implements Serializable {

	private static final long serialVersionUID = 1093698498218973841L;
	private PagamentoId id;
	private Cliente cliente;
	private Curso curso;

	public Pagamento() {
	}

	public Pagamento(PagamentoId id, Cliente cliente, Curso curso) {
		this.id = id;
		this.cliente = cliente;
		this.curso = curso;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cpf", column = @Column(name = "CPF", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "cdcurso", column = @Column(name = "CDCURSO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "datainscricao", column = @Column(name = "DATAINSCRICAO", nullable = false, length = 10)) })
	public PagamentoId getId() {
		return this.id;
	}

	public void setId(PagamentoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CPF", nullable = false, insertable = false, updatable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDCURSO", nullable = false, insertable = false, updatable = false)
	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	@Override
	public String toString() {
		return cliente.toString() 
				+ "\n" + curso.toString()
				+ "\nInscrição feita em: " + id.getDatainscricao();
	}
}
