package com.abctreinamentos;
// Generated 02/01/2019 15:52:06 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PagamentoId generated by hbm2java
 */
@Embeddable
public class PagamentoId implements Serializable {

	private static final long serialVersionUID = 2381298685215435199L;
	private long cpf;
	private int cdcurso;
	private String datainscricao;

	public PagamentoId() {
	}

	public PagamentoId(long cpf, int cdcurso, String datainscricao) {
		this.cpf = cpf;
		this.cdcurso = cdcurso;
		this.datainscricao = datainscricao;
	}

	@Column(name = "CPF", nullable = false, precision = 22, scale = 0)
	public long getCpf() {
		return this.cpf;
	}

	public void setCpf(long cpf) {
		this.cpf = cpf;
	}

	@Column(name = "CDCURSO", nullable = false, precision = 22, scale = 0)
	public int getCdcurso() {
		return this.cdcurso;
	}

	public void setCdcurso(int cdcurso) {
		this.cdcurso = cdcurso;
	}

	@Column(name = "DATAINSCRICAO", nullable = false, length = 10)
	public String getDatainscricao() {
		return this.datainscricao;
	}

	public void setDatainscricao(String datainscricao) {
		this.datainscricao = datainscricao;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + cdcurso;
		result = prime * result + (int) (cpf ^ (cpf >>> 32));
		result = prime * result + ((datainscricao == null) ? 0 : datainscricao.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PagamentoId other = (PagamentoId) obj;
		if (cdcurso != other.cdcurso)
			return false;
		if (cpf != other.cpf)
			return false;
		if (datainscricao == null) {
			if (other.datainscricao != null)
				return false;
		} else if (!datainscricao.equals(other.datainscricao))
			return false;
		return true;
	}
}
